services:
  source-db:
    image: postgres
    environment:
      POSTGRES_DB: source
      POSTGRES_USER: ${SOURCE_DB_USER}
      POSTGRES_PASSWORD: ${SOURCE_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./db_init/source_init.sql:/docker-entrypoint-initdb.d/source_init.sql
      - source_data:/var/lib/postgresql/data

  target-db:
    image: postgres
    environment:
      POSTGRES_DB: target
      POSTGRES_USER: ${TARGET_DB_USER}
      POSTGRES_PASSWORD: ${TARGET_DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ./db_init/target_init.sql:/docker-entrypoint-initdb.d/init.sql
      - target_data:/var/lib/postgresql/data

volumes:
  source_data:
  target_data:
